<?xml version="1.0"?>
<File xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Extension=".tpa" TDC="Test Parameter File for ATCL test cases" TDL="ATCL" Type="Test Parameter File" Version="1.0">
  <ParamSets Name="TC_SetVerdictNET">
    <ParamSet Name="TC_SetVerdictNET" OID="TC_SetVerdictNET">
      <UserRecord Name="Verdict" InstanceName="Verdict" Comment="The result of the Test Case" Functionality="Collection" URType="Etas.Eas.Atcl.Interfaces.Types.TypeSutCollectionUserRecord">
        <Parameter Name="Verdicts" InstanceName="selection_Rarrcstr" Comment="" DataType="charstring" IsLblChangeable="false" Lbl="Verdicts" MaxValue="" MinValue="" ObjectType="Array">
          <Array Size="5">
            <V>
              <Sc I="0" Val="Pass" />
              <Sc I="1" Val="Fail" />
              <Sc I="2" Val="Inconc" />
              <Sc I="3" Val="Error" />
              <Sc I="4" Val="None" />
            </V>
          </Array>
          <DefArray Size="5">
            <V>
              <Sc I="0" Val="Pass" />
              <Sc I="1" Val="Fail" />
              <Sc I="2" Val="Inconc" />
              <Sc I="3" Val="Error" />
              <Sc I="4" Val="None" />
            </V>
          </DefArray>
        </Parameter>
        <Parameter Name="Current Verdict" InstanceName="selected_Rcstr" Comment="" DataType="charstring" IsLblChangeable="false" Lbl="Current Verdict" MaxValue="" MinValue="" ObjectType="Scalar">
          <Scalar Value="Pass" />
          <DefScalar Value="Pass" />
        </Parameter>
      </UserRecord>
      <Parameter Name="Duration" InstanceName="Duration" Comment="Duration time in seconds for this test case. Zero means as fast as possible" DataType="integer" IsLblChangeable="false" Lbl="Duration" MaxValue="2147483647" MinValue="0" ObjectType="Scalar" Unit="">
        <Scalar Value="0" />
        <DefScalar Value="0" />
      </Parameter>
    </ParamSet>
  </ParamSets>
</File>