<?xml version="1.0"?>
<File xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Extension=".tpa" TDC="Test Parameter File for ATCL test cases" TDL="Python" Type="Test Parameter File" Version="1.0">
  <ParamSets Name="TC_HelloWorld">
    <ParamSet Name="TC_HelloWorld" OID="TC_HelloWorld">
      <Parameter Name="A Test Parameter" InstanceName="A Test Parameter" Comment="An example of parameterization usage, in this case a string" DataType="charstring" IsLblChangeable="false" Lbl="--" MaxValue="" MinValue="" ObjectType="Scalar">
        <Scalar Value="Hello World!" />
        <DefScalar Value="Hello World!" />
      </Parameter>
      <Parameter Name="Upper Case conversion" InstanceName="Upper Case conversion" Comment="Determines if the Test Parameter shall be converted to upper case " DataType="boolean" IsLblChangeable="false" Lbl="--" MaxValue="True" MinValue="False" ObjectType="Scalar">
        <Scalar Value="True" />
        <DefScalar Value="True" />
      </Parameter>
      <Parameter Name="Sleep Time before Evaluation" InstanceName="Sleep Time before Evaluation" Comment="Waiting time before executing the evaluation" DataType="integer" IsLblChangeable="false" Lbl="--" MaxValue="10" MinValue="0" ObjectType="Scalar" Unit="s">
        <Scalar Value="1" />
        <DefScalar Value="1" />
      </Parameter>
    </ParamSet>
  </ParamSets>
</File>