<?xml version="1.0"?>
<File xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Extension=".tpa" TDC="Test Parameter File for ATCL test cases" TDL="Python" Type="Test Parameter File" Version="1.0">
  <ParamSets Name="TC_FuelPump">
    <ParamSet Name="TC_FuelPump" OID="TC_FuelPump">
      <Parameter Name="Engine Speed" InstanceName="Engine Speed" Comment="Parameter Setting the Engine Speed to a constant value" DataType="float" IsLblChangeable="false" Lbl="ENGSPD" MaxValue="10000" MinValue="0" ObjectType="Scalar" Unit="rpm">
        <Scalar Value="0" />
        <DefScalar Value="0" />
      </Parameter>
      <Parameter Name="Wait time for Relaxation" InstanceName="Wait time for Relaxation" Comment="Standard Wating time" DataType="integer" IsLblChangeable="false" Lbl="--" MaxValue="1000" MinValue="0" ObjectType="Scalar" Unit="s">
        <Scalar Value="2" />
        <DefScalar Value="2" />
      </Parameter>
    </ParamSet>
  </ParamSets>
</File>