<?xml version="1.0" encoding="UTF-8" ?>

<File Extension="tpa" TDC="Telelogic TAU/Tester V2.3" TDL="TTCN-3" Type="Test Parameter File"
         Version="1.0">
    <ParamSets Name="TC_J1699">
        <ParamSet Comment="" Name="default" OID="TC_J1699">
            <UserRecord Comment="sends sequences of messages and verify response for every message"
                     Functionality="" InstanceName="modpar_sendResponseTest_RUR" Name="sendResponseTest"
                     URType="TE_J1699.Type_SendResponseTest_RUR">
                <DynamicArray Functionality="" InstanceName="message_RDARUR" Name="message_RDARUR"
                         Type="TE_J1699.Type_SendResponse_RDARUR">
                    <Arr Size="1">
                        <ArrEl I="0">
                            <UserRecord Comment="send message and verify responses"
                                     Functionality="" InstanceName="0" Name="msg1"
                                     URType="TE_J1699.Type_SendResponse_RUR">
                                <UserRecord Comment="message to be sent to OCT" Functionality=""
                                         InstanceName="sendMsg_RUR" Name="sendmsg"
                                         URType="TE_J1699.Type_Message_RUR">
                                    <Parameter Comment="" DataType="charstring" DefaultLbl=""
                                             InstanceName="msgName_Rcstr" IsLblChangeable="false"
                                             Lbl="" MaxValue="" MinValue="" Name="name"
                                             ObjectType="Scalar" Unit="">
                                        <Scalar Value="ACTION" />
                                        <DefScalar Value="ACTION" />
                                        <History>
                                            <Entry Action="Created by TCD" Comment=""
                                                     Date="2005.08.30 16:11" Order="0"
                                                     User="frwohnfu" />
                                        </History>
                                    </Parameter>
                                    <Parameter Comment="" DataType="charstring" DefaultLbl=""
                                             InstanceName="msgArgs_Rarrcstr" IsLblChangeable="false"
                                             Lbl="" MaxValue="" MinValue="" Name="args"
                                             ObjectType="Array" Unit="">
                                        <Array Size="1">
                                            <V>
                                                <Sc I="0" Val="IgnitionOn" />
                                            </V>
                                        </Array>
                                        <DefArray Size="1">
                                            <V>
                                                <Sc I="0" Val="IgnitionOn" />
                                            </V>
                                        </DefArray>
                                        <History>
                                            <Entry Action="Created by TCD" Comment=""
                                                     Date="2005.08.30 16:11" Order="0"
                                                     User="frwohnfu" />
                                        </History>
                                    </Parameter>
                                </UserRecord>
                                <UserRecord Comment="response message to be verified"
                                         Functionality="" InstanceName="rcvMsg_RUR"
                                         Name="rcvmsg" URType="TE_J1699.Type_Message_RUR">
                                    <Parameter Comment="" DataType="charstring" DefaultLbl=""
                                             InstanceName="msgName_Rcstr" IsLblChangeable="false"
                                             Lbl="" MaxValue="" MinValue="" Name="name"
                                             ObjectType="Scalar" Unit="">
                                        <Scalar Value="RE" />
                                        <DefScalar Value="RE" />
                                        <History>
                                            <Entry Action="Created by TCD" Comment=""
                                                     Date="2005.08.30 16:11" Order="0"
                                                     User="frwohnfu" />
                                        </History>
                                    </Parameter>
                                    <Parameter Comment="" DataType="charstring" DefaultLbl=""
                                             InstanceName="msgArgs_Rarrcstr" IsLblChangeable="false"
                                             Lbl="" MaxValue="" MinValue="" Name="args"
                                             ObjectType="Array" Unit="">
                                        <Array Size="1">
                                            <V>
                                                <Sc I="0" Val="OK" />
                                            </V>
                                        </Array>
                                        <DefArray Size="1">
                                            <V>
                                                <Sc I="0" Val="OK" />
                                            </V>
                                        </DefArray>
                                        <History>
                                            <Entry Action="Created by TCD" Comment=""
                                                     Date="2005.08.30 16:11" Order="0"
                                                     User="frwohnfu" />
                                        </History>
                                    </Parameter>
                                </UserRecord>
                            </UserRecord>
                        </ArrEl>
                    </Arr>
                    <DefArr Size="1">
                        <ArrEl I="0">
                            <UserRecord Comment="send message and verify responses"
                                     Functionality="" InstanceName="0" Name="msg1"
                                     URType="TE_J1699.Type_SendResponse_RUR">
                                <UserRecord Comment="message to be sent to OCT" Functionality=""
                                         InstanceName="sendMsg_RUR" Name="sendmsg"
                                         URType="TE_J1699.Type_Message_RUR">
                                    <Parameter Comment="" DataType="charstring" DefaultLbl=""
                                             InstanceName="msgName_Rcstr" IsLblChangeable="false"
                                             Lbl="" MaxValue="" MinValue="" Name="name"
                                             ObjectType="Scalar" Unit="">
                                        <Scalar Value="ACTION" />
                                        <DefScalar Value="ACTION" />
                                        <History>
                                            <Entry Action="Created by TCD" Comment=""
                                                     Date="2005.08.30 16:11" Order="0"
                                                     User="frwohnfu" />
                                        </History>
                                    </Parameter>
                                    <Parameter Comment="" DataType="charstring" DefaultLbl=""
                                             InstanceName="msgArgs_Rarrcstr" IsLblChangeable="false"
                                             Lbl="" MaxValue="" MinValue="" Name="args"
                                             ObjectType="Array" Unit="">
                                        <Array Size="1">
                                            <V>
                                                <Sc I="0" Val="IgnitionOn" />
                                            </V>
                                        </Array>
                                        <DefArray Size="1">
                                            <V>
                                                <Sc I="0" Val="IgnitionOn" />
                                            </V>
                                        </DefArray>
                                        <History>
                                            <Entry Action="Created by TCD" Comment=""
                                                     Date="2005.08.30 16:11" Order="0"
                                                     User="frwohnfu" />
                                        </History>
                                    </Parameter>
                                </UserRecord>
                                <UserRecord Comment="response message to be verified"
                                         Functionality="" InstanceName="rcvMsg_RUR"
                                         Name="rcvmsg" URType="TE_J1699.Type_Message_RUR">
                                    <Parameter Comment="" DataType="charstring" DefaultLbl=""
                                             InstanceName="msgName_Rcstr" IsLblChangeable="false"
                                             Lbl="" MaxValue="" MinValue="" Name="name"
                                             ObjectType="Scalar" Unit="">
                                        <Scalar Value="RE" />
                                        <DefScalar Value="RE" />
                                        <History>
                                            <Entry Action="Created by TCD" Comment=""
                                                     Date="2005.08.30 16:11" Order="0"
                                                     User="frwohnfu" />
                                        </History>
                                    </Parameter>
                                    <Parameter Comment="" DataType="charstring" DefaultLbl=""
                                             InstanceName="msgArgs_Rarrcstr" IsLblChangeable="false"
                                             Lbl="" MaxValue="" MinValue="" Name="args"
                                             ObjectType="Array" Unit="">
                                        <Array Size="1">
                                            <V>
                                                <Sc I="0" Val="OK" />
                                            </V>
                                        </Array>
                                        <DefArray Size="1">
                                            <V>
                                                <Sc I="0" Val="OK" />
                                            </V>
                                        </DefArray>
                                        <History>
                                            <Entry Action="Created by TCD" Comment=""
                                                     Date="2005.08.30 16:11" Order="0"
                                                     User="frwohnfu" />
                                        </History>
                                    </Parameter>
                                </UserRecord>
                            </UserRecord>
                        </ArrEl>
                    </DefArr>
                </DynamicArray>
            </UserRecord>
        </ParamSet>
    </ParamSets>
</File>

