<?xml version="1.0"?>
<File xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Extension=".tpa" TDC="Test Parameter File for ATCL test cases" TDL="ATCL" Type="Test Parameter File" Version="1.0">
  <ParamSets Name="TC_ReportingRequirements">
    <ParamSet Name="TC_ReportingRequirements" OID="TC_ReportingRequirements">
      <Parameter Name="ShowLargeTable" InstanceName="ShowLargeTable" Comment="Defines wether the large table is shown." DataType="boolean" IsLblChangeable="false" Lbl="" MaxValue="True" MinValue="False" ObjectType="Scalar">
        <Scalar Value="True" />
        <DefScalar Value="True" />
      </Parameter>
    </ParamSet>
  </ParamSets>
</File>