<?xml version="1.0" encoding="UTF-8" ?>

<File Extension="tpa" TDC="Telelogic TAU/Tester V2.4" TDL="TTCN-3" Type="Test Parameter File"
         Version="1.0">
    <ParamSets Name="TC_Inca5">
        <ParamSet Comment="" Name="default" OID="TC_Inca5">
            <Parameter Comment="Radgeschwindigkeit vorne links" DataType="float" DefaultLbl="v_vl"
                     InstanceName="modpar_dummy_Rflt" IsLblChangeable="true" Lbl="v_vl"
                     MaxValue="360.0" MinValue="0.0" Name="Geschwindigkeit vorne links"
                     ObjectType="Scalar" Unit="km/h">
                <Scalar Value="100.0" />
                <DefScalar Value="100.0" />
                <History>
                    <Entry Action="Created by TCD" Comment="" Date="2005.09.06 09:10"
                             Order="0" User="frwohnfu" />
                </History>
            </Parameter>
        </ParamSet>
    </ParamSets>
</File>

