<?xml version="1.0"?>
<File xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Extension=".tpa" TDC="Test Parameter File for ATCL test cases" TDL="Python" Type="Test Parameter File" Version="1.0">
  <ParamSets Name="TC_PY_Template">
    <ParamSet Name="TC_PY_Template" OID="TC_PY_Template">
      <DynamicArray Name="List of TorqueSets" InstanceName="List of TorqueSets" Comment="Dynamic Array List of Torque sets" Type="Etas.Eas.Atcl.Interfaces.Types.TypeSutUserRecord">
        <Arr Size="1">
          <ArrEl I="0">
            <UserRecord Name="TorqueSets" InstanceName="TorqueSets" Comment="Set of orque elements with limits" Functionality="AtclUserRecord" URType="Etas.Eas.Atcl.Interfaces.Types.TypeSutUserRecord">
              <Parameter Name="Torque" InstanceName="Torque" Comment="The torque of the A/C" DataType="float" IsLblChangeable="false" Lbl="AirConditionTorque" MaxValue="0" MinValue="-100" ObjectType="Scalar" Unit="">
                <Scalar Value="-10" />
                <DefScalar Value="-10" />
              </Parameter>
              <Parameter Name="MinRPMValue" InstanceName="MinRPMValue" Comment="The minimum rpm to pass the test" DataType="float" IsLblChangeable="false" Lbl="RPMMinValue" MaxValue="700" MinValue="300" ObjectType="Scalar" Unit="">
                <Scalar Value="650" />
                <DefScalar Value="650" />
              </Parameter>
              <Parameter Name="MaxRPMValue" InstanceName="MaxRPMValue" Comment="The maximum rpm to pass the test" DataType="float" IsLblChangeable="false" Lbl="RPMMaxValue" MaxValue="1000" MinValue="500" ObjectType="Scalar" Unit="">
                <Scalar Value="750" />
                <DefScalar Value="750" />
              </Parameter>
            </UserRecord>
          </ArrEl>
        </Arr>
        <DefArr Size="1">
          <ArrEl I="0">
            <UserRecord Name="TorqueSets" InstanceName="TorqueSets" Comment="Set of orque elements with limits" Functionality="AtclUserRecord" URType="Etas.Eas.Atcl.Interfaces.Types.TypeSutUserRecord">
              <Parameter Name="Torque" InstanceName="Torque" Comment="The torque of the A/C" DataType="float" IsLblChangeable="false" Lbl="AirConditionTorque" MaxValue="0" MinValue="-100" ObjectType="Scalar" Unit="">
                <Scalar Value="-10" />
                <DefScalar Value="-10" />
              </Parameter>
              <Parameter Name="MinRPMValue" InstanceName="MinRPMValue" Comment="The minimum rpm to pass the test" DataType="float" IsLblChangeable="false" Lbl="RPMMinValue" MaxValue="700" MinValue="300" ObjectType="Scalar" Unit="">
                <Scalar Value="650" />
                <DefScalar Value="650" />
              </Parameter>
              <Parameter Name="MaxRPMValue" InstanceName="MaxRPMValue" Comment="The maximum rpm to pass the test" DataType="float" IsLblChangeable="false" Lbl="RPMMaxValue" MaxValue="1000" MinValue="500" ObjectType="Scalar" Unit="">
                <Scalar Value="750" />
                <DefScalar Value="750" />
              </Parameter>
            </UserRecord>
          </ArrEl>
        </DefArr>
      </DynamicArray>
      <UserRecord Name="PIDParams" InstanceName="PIDParams" Comment="Set of idlecontoller parameters" Functionality="AtclUserRecord" URType="Etas.Eas.Atcl.Interfaces.Types.TypeSutUserRecord">
        <Parameter Name="Idle" InstanceName="Idle" Comment="" DataType="float" IsLblChangeable="false" Lbl="IIdle" MaxValue="1" MinValue="0" ObjectType="Scalar" Unit="">
          <Scalar Value="0.0005" />
          <DefScalar Value="0.0005" />
        </Parameter>
        <Parameter Name="Pdle" InstanceName="Pdle" Comment="" DataType="float" IsLblChangeable="false" Lbl="PIdle" MaxValue="1" MinValue="0" ObjectType="Scalar" Unit="">
          <Scalar Value="0.02" />
          <DefScalar Value="0.02" />
        </Parameter>
      </UserRecord>
    </ParamSet>
  </ParamSets>
</File>