<?xml version="1.0" encoding="UTF-8" ?>

<File Extension="tpa" TDC="Telelogic TAU/Tester V2.3" TDL="TTCN-3" Type="Test Parameter File"
         Version="1.0">
    <ParamSets Name="TC_FACD">
        <ParamSet Comment="" Name="default" OID="TC_FACD">
            <Parameter Comment="Radgeschwindigkeit vorne links" DataType="float" DefaultLbl="v_vl"
                     InstanceName="modpar_dummy_Rflt" IsLblChangeable="true" Lbl="v_vl"
                     MaxValue="360.0" MinValue="0.0" Name="Geschwindigkeit vorne links"
                     ObjectType="Scalar" Unit="km/h">
                <Scalar Value="100.0" />
                <DefScalar Value="100.0" />
                <History>
                    <Entry Action="Created by TCD" Comment="" Date="2005.08.16 13:40"
                             Order="0" User="stpantsc" />
                </History>
            </Parameter>
            <Parameter Comment="You may attach the debugger, while the Message Box stops the execution."
                     DataType="boolean" DefaultLbl="Debug_Action" InstanceName="modpar_debugAction_Rbool"
                     IsLblChangeable="true" Lbl="Debug_Action" MaxValue="" MinValue=""
                     Name="debug action" ObjectType="Scalar" Unit="">
                <Scalar Value="false" />
                <DefScalar Value="false" />
                <History>
                    <Entry Action="Created by TCD" Comment="" Date="2005.08.16 13:40"
                             Order="0" User="stpantsc" />
                </History>
            </Parameter>
        </ParamSet>
    </ParamSets>
</File>

